### ISSUE TITLE
CONST does not work as DIM's address

### ISSUE THREAD

**Issue by orlof** [neilsf/xc-basic3#193] opened 2022-07-01 19:47 UTC
This may be a bug or feature wish, but I assumed this would work:

```
CONST SCRMEM = 1024
DIM ctime AS BYTE @SCRMEM
ctime = 1
```
Fatal assembly error: Source is not resolvable.

**Comment by neilsf** [comment] 2022-07-02 07:38
Duplicate of #63

**Closed by neilsf** 2022-07-02 07:38 UTC
